package ulbra.hard.test;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ulbra.hard.model.bean.Fornecedor;
import ulbra.hard.model.dao.FornecedorDAO;

/**
 *
 * @author @andre_ments
 */
public class frmFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form frmUsuarios
     */
    enum PHASE {
        NONE,NEW,VIEW,EDIT
    }

    PHASE registerPhase = PHASE.NONE;

    public frmFornecedores() {
        initComponents();
        this.getContentPane().setBackground(new Color(20, 20, 20));
        populateUsersTable();
    }

    private boolean checkParameters() {
        if (txtSocialReason.getText().isEmpty() || txtFantasyName.getText().isEmpty() || txtPhone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Algum campo está vazio.");
            return false;
        }
        return true;
    }

    private void populateUsersTable() {
        DefaultTableModel model = (DefaultTableModel) tableFornecedores.getModel();
        model.setNumRows(0);

        FornecedorDAO dao = new FornecedorDAO();

        for (Fornecedor f : dao.findAll()) {
            model.addRow(new Object[]{
                f.getId(),
                f.getSocialReason(),
                f.getFantasyName(),
                f.getPhone(),
                f.getEmail(),
                f.getManager()
            });

        }
    }

    private void populateUsersTableCustom() {
        DefaultTableModel model = (DefaultTableModel) tableFornecedores.getModel();
        model.setNumRows(0);

        FornecedorDAO dao = new FornecedorDAO();

        for (Fornecedor f : dao.findAllByFilter(String.valueOf(comboSearch.getSelectedItem()), txtSearch.getText())) {
            model.addRow(new Object[]{
                f.getId(),
                f.getSocialReason(),
                f.getFantasyName(),
                f.getPhone(),
                f.getEmail(),
                f.getManager()
            });

        }

    }

    private void updateControls(PHASE phase) {
        switch (phase) {
            case NONE:
                txtSocialReason.setEditable(false);
                txtFantasyName.setEditable(false);
                txtPhone.setEditable(false);
                txtEmail.setEditable(false);
                txtManager.setEditable(false);
                btNew.setEnabled(true);
                btSave.setEnabled(false);
                btEdit.setEnabled(false);
                btDelete.setEnabled(false);
                btCancel.setEnabled(false);

                txtId.setText("");
                txtSocialReason.setText("");
                txtFantasyName.setText("");
                txtPhone.setText("");
                txtEmail.setText("");
                txtManager.setText("");
                break;

            case NEW:
                txtSocialReason.setEditable(true);
                txtFantasyName.setEditable(true);
                txtPhone.setEditable(true);
                txtEmail.setEditable(true);
                txtManager.setEditable(true);
                btNew.setEnabled(false);
                btSave.setEnabled(true);
                btEdit.setEnabled(false);
                btDelete.setEnabled(false);
                btCancel.setEnabled(true);
                break;

            case VIEW:
                txtSocialReason.setEditable(false);
                txtFantasyName.setEditable(false);
                txtPhone.setEditable(false);
                txtEmail.setEditable(false);
                txtManager.setEditable(false);
                btNew.setEnabled(false);
                btSave.setEnabled(false);
                btEdit.setEnabled(true);
                btDelete.setEnabled(true);
                btCancel.setEnabled(true);
                break;

            case EDIT:
                txtSocialReason.setEditable(true);
                txtFantasyName.setEditable(true);
                txtPhone.setEditable(true);
                txtEmail.setEditable(true);
                txtManager.setEditable(true);
                btNew.setEnabled(false);
                btSave.setEnabled(true);
                btEdit.setEnabled(false);
                btDelete.setEnabled(false);
                btCancel.setEnabled(true);
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabcFornecedores = new javax.swing.JTabbedPane();
        tabFornecedoresReg = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtSocialReason = new javax.swing.JTextField();
        txtFantasyName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btNew = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtManager = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        tabFornecedoresList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFornecedores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        comboSearch = new javax.swing.JComboBox<>();
        btSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabFornecedoresReg.setBackground(new java.awt.Color(255, 255, 255));
        tabFornecedoresReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "ID:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, -1));

        txtSocialReason.setEditable(false);
        txtSocialReason.setBackground(new java.awt.Color(255, 255, 255));
        txtSocialReason.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Razão Social:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtSocialReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 378, -1));

        txtFantasyName.setEditable(false);
        txtFantasyName.setBackground(new java.awt.Color(255, 255, 255));
        txtFantasyName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Nome Fantasia:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtFantasyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, -1));

        txtPhone.setEditable(false);
        txtPhone.setBackground(new java.awt.Color(255, 255, 255));
        txtPhone.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contato/Telefone:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 380, -1));

        btNew.setText("NOVO");
        btNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNewMouseClicked(evt);
            }
        });
        tabFornecedoresReg.add(btNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 70, 40));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "E-mail:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 380, -1));

        txtManager.setEditable(false);
        txtManager.setBackground(new java.awt.Color(255, 255, 255));
        txtManager.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gerente/Comercial:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        tabFornecedoresReg.add(txtManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 380, -1));

        jPanel1.setBackground(new java.awt.Color(228, 238, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSave.setText("salvar");
        btSave.setEnabled(false);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        btEdit.setText("editar");
        btEdit.setEnabled(false);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel1.add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 60, 30));

        btCancel.setText("cancelar");
        btCancel.setEnabled(false);
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 30));

        btDelete.setText("excluir");
        btDelete.setEnabled(false);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 70, 30));

        tabFornecedoresReg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 400, 50));

        tabcFornecedores.addTab("cadastrar", tabFornecedoresReg);

        tabFornecedoresList.setBackground(new java.awt.Color(255, 255, 255));
        tabFornecedoresList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "razaoSocial", "nomeFantasia", "telefone", "email", "gerente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableFornecedores);

        tabFornecedoresList.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 380, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "socialReason", "fantasyName", "phone", "email", "manager" }));
        jPanel2.add(comboSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btSearch.setText("Buscar");
        btSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSearchMouseClicked(evt);
            }
        });
        jPanel2.add(btSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        txtSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        tabFornecedoresList.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 90));

        tabcFornecedores.addTab("listar", tabFornecedoresList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabcFornecedores)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabcFornecedores)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNewMouseClicked
        registerPhase = PHASE.NEW;
        updateControls(registerPhase);
    }//GEN-LAST:event_btNewMouseClicked

    private void tableFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFornecedoresMouseClicked

        if (tableFornecedores.getSelectedRow() != -1) {

            txtId.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 0).toString());
            txtSocialReason.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 1).toString());
            txtFantasyName.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 2).toString());
            txtPhone.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 3).toString());
            txtEmail.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 4).toString());
            txtManager.setText(tableFornecedores.getValueAt(tableFornecedores.getSelectedRow(), 5).toString());

            registerPhase = PHASE.VIEW;
            updateControls(registerPhase);

            tabcFornecedores.setSelectedIndex(0);
        }
    }//GEN-LAST:event_tableFornecedoresMouseClicked

    private void btSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSearchMouseClicked
        if (txtSearch.getText() != "") {
            populateUsersTableCustom();
        }
    }//GEN-LAST:event_btSearchMouseClicked

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if (checkParameters()) {
            Produto p = new Produto();
            ProdutoDAO dao = new ProdutoDAO();
            switch (registerPhase) {
                case EDIT:
                    p.setId(Integer.parseInt(txtId.getText()));
                case NEW:
                    p.setDescription(txtDescription.getText());
                    p.setQuantity(Integer.parseInt(txtQuantity.getText()));
                    String priceFix = txtPrice.getText().replaceAll("\\.", "").replaceAll(",", ".");
                    p.setPrice(Double.parseDouble(priceFix));
                    p.setCategory(selectedCategory);
                    p.setSupplier(selectedSupplier);

                    dao.save(p);
                    break;
            }

            registerPhase = PHASE.NONE;
            updateControls(registerPhase);
            populateProductsTable();
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        registerPhase = PHASE.EDIT;
        updateControls(registerPhase);
    }//GEN-LAST:event_btEditActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        registerPhase = PHASE.NONE;
        updateControls(registerPhase);
    }//GEN-LAST:event_btCancelActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        ProdutoDAO dao = new ProdutoDAO();

        dao.remove(Integer.parseInt(txtId.getText()));

        registerPhase = PHASE.NONE;
        updateControls(registerPhase);

        populateProductsTable();
    }//GEN-LAST:event_btDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> comboSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tabFornecedoresList;
    private javax.swing.JPanel tabFornecedoresReg;
    private javax.swing.JTabbedPane tabcFornecedores;
    private javax.swing.JTable tableFornecedores;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFantasyName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtManager;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSocialReason;
    // End of variables declaration//GEN-END:variables
}
